// This file is gitignored - your actual data goes here
// For CI/CD: Copy data.example.ts to data.ts before building
// Or use: cp app/lib/data.example.ts app/lib/data.ts

import { MusicTrack, Album, Sermon, Event, GalleryItem, Scripture, SocialLink } from '@/app/types';

export const musicTracks: MusicTrack[] = [
  {
    id: 'umi-nam',
    title: 'Umi Nam',
    album: 'Single',
    duration: '4:15',
    audioUrl: '/audio/umi-nam.mp3',
    coverImage: '/images/umi-nami.jpeg',
    releaseDate: '2025-08-18',
    featured: true,
    platforms: [
      { name: 'Spotify', url: 'https://open.spotify.com/track/3Hw6mfyKZbCeHVvxwQXw6m?si=c89158999e9b4c56' },
      { name: 'Apple Music', url: 'https://music.apple.com/us/song/umi-nami-engumthokozisi/1833488973' },
      { name: 'YouTube Music', url: 'https://youtu.be/0ZD0tv5ZfuU?si=ffXqBq5BDAy4GDic' },
    ],
  },
  // Hymns & Melodies Vol. 1 Tracks
  {
    id: 'yamkel-indumiso',
    title: 'Yamkel\'indumiso (Live)',
    album: 'Hymns & Melodies Vol. 1',
    duration: '6:50',
    audioUrl: '/audio/hymns-melodies-vol1/yamkel-indumiso.mp3',
    coverImage: '/images/h&m-replacement.jpeg',
    releaseDate: '2024-04-15',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
      { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
    ],
  },
  {
    id: 'lalelani-izinceku',
    title: 'Lalelani Izinceku (Live)',
    album: 'Hymns & Melodies Vol. 1',
    duration: '6:10',
    audioUrl: '/audio/hymns-melodies-vol1/lalelani-izinceku.mp3',
    coverImage: '/images/h&m-replacement.jpeg',
    releaseDate: '2024-04-15',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
      { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
    ],
  },
  {
    id: 'akumnyama-xha-ukhona',
    title: 'Akumnyama Xha Ukhona (Live)',
    album: 'Hymns & Melodies Vol. 1',
    duration: '5:40',
    audioUrl: '/audio/hymns-melodies-vol1/akumnyama-xha-ukhona.mp3',
    coverImage: '/images/h&m-replacement.jpeg',
    releaseDate: '2024-04-15',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
      { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
    ],
  },
  {
    id: 'hymn-medley',
    title: 'Hymn Medley (Live)',
    album: 'Hymns & Melodies Vol. 1',
    duration: '8:36',
    audioUrl: '/audio/hymns-melodies-vol1/hymn-medley.mp3',
    coverImage: '/images/h&m-replacement.jpeg',
    releaseDate: '2024-04-15',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
      { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
    ],
  },
  {
    id: 'aneliswe',
    title: 'Aneliswe (Live)',
    album: 'Hymns & Melodies Vol. 1',
    duration: '5:56',
    audioUrl: '/audio/hymns-melodies-vol1/aneliswe.mp3',
    coverImage: '/images/h&m-replacement.jpeg',
    releaseDate: '2024-04-15',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
      { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
    ],
  },
  {
    id: 'nxa-ebizwa-ama-gama',
    title: 'Nxa Ebizwa Ama Gama (Live)',
    album: 'Hymns & Melodies Vol. 1',
    duration: '6:00',
    audioUrl: '/audio/hymns-melodies-vol1/nxa-ebizwa-ama-gama.mp3',
    coverImage: '/images/h&m-replacement.jpeg',
    releaseDate: '2024-04-15',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
      { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
    ],
  },
  {
    id: 'thixo-ova-izikhungo',
    title: 'Thixo Ova Izikhungo (Live)',
    album: 'Hymns & Melodies Vol. 1',
    duration: '5:26',
    audioUrl: '/audio/hymns-melodies-vol1/thixo-ova-izikhungo.mp3',
    coverImage: '/images/h&m-replacement.jpeg',
    releaseDate: '2024-04-15',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
      { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
    ],
  },
  {
    id: 'oko-kwanga-kulumkile',
    title: 'Oko Kwanga Kulumkile (Live)',
    album: 'Hymns & Melodies Vol. 1',
    duration: '6:38',
    audioUrl: '/audio/hymns-melodies-vol1/oko-kwanga-kulumkile.mp3',
    coverImage: '/images/h&m-replacement.jpeg',
    releaseDate: '2024-04-15',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
      { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
    ],
  },
  {
    id: 'iba-nodumo',
    title: 'Iba Nodumo (Live)',
    album: 'Hymns & Melodies Vol. 1',
    duration: '3:56',
    audioUrl: '/audio/hymns-melodies-vol1/iba-nodumo.mp3',
    coverImage: '/images/h&m-replacement.jpeg',
    releaseDate: '2024-04-15',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
      { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
    ],
  },
  {
    id: 'bulelani',
    title: 'Bulelani (Live)',
    album: 'Hymns & Melodies Vol. 1',
    duration: '6:28',
    audioUrl: '/audio/hymns-melodies-vol1/bulelani.mp3',
    coverImage: '/images/h&m-replacement.jpeg',
    releaseDate: '2024-04-15',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
      { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
    ],
  },
  // Hymns & Melodies Vol. 2 Tracks
  {
    id: 'ungukumkani',
    title: 'Ungukumkani',
    album: 'Hymns & Melodies Vol. 2',
    duration: '5:34',
    audioUrl: '/audio/hymns-melodies-vol2/ungukumkani.mp3',
    coverImage: '/images/h&m-v2-replacement.jpeg',
    releaseDate: '2024-05-22',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
      { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
    ],
  },
  {
    id: 'uthweswe',
    title: 'Uthweswe',
    album: 'Hymns & Melodies Vol. 2',
    duration: '5:40',
    audioUrl: '/audio/hymns-melodies-vol2/uthweswe.mp3',
    coverImage: '/images/h&m-v2-replacement.jpeg',
    releaseDate: '2024-05-22',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
      { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
    ],
  },
  {
    id: 'thixo-ulilanga',
    title: 'Thixo Ulilanga',
    album: 'Hymns & Melodies Vol. 2',
    duration: '6:01',
    audioUrl: '/audio/hymns-melodies-vol2/thixo-ulilanga.mp3',
    coverImage: '/images/h&m-v2-replacement.jpeg',
    releaseDate: '2024-05-22',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
      { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
    ],
  },
  {
    id: 'ndingu-mfokazi',
    title: 'Ndingu Mfokazi',
    album: 'Hymns & Melodies Vol. 2',
    duration: '4:48',
    audioUrl: '/audio/hymns-melodies-vol2/ndingu-mfokazi.mp3',
    coverImage: '/images/h&m-v2-replacement.jpeg',
    releaseDate: '2024-05-22',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
      { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
    ],
  },
  {
    id: 'mnqamlezo',
    title: 'Mnqamlezo',
    album: 'Hymns & Melodies Vol. 2',
    duration: '8:15',
    audioUrl: '/audio/hymns-melodies-vol2/mnqamlezo.mp3',
    coverImage: '/images/h&m-v2-replacement.jpeg',
    releaseDate: '2024-05-22',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
      { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
    ],
  },
  {
    id: 'makabongwe',
    title: 'Makabongwe',
    album: 'Hymns & Melodies Vol. 2',
    duration: '9:39',
    audioUrl: '/audio/hymns-melodies-vol2/makabongwe.mp3',
    coverImage: '/images/h&m-v2-replacement.jpeg',
    releaseDate: '2024-05-22',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
      { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
    ],
  },
  {
    id: 'jabulani',
    title: 'Jabulani',
    album: 'Hymns & Melodies Vol. 2',
    duration: '5:05',
    audioUrl: '/audio/hymns-melodies-vol2/jabulani.mp3',
    coverImage: '/images/h&m-v2-replacement.jpeg',
    releaseDate: '2024-05-22',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
      { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
    ],
  },
  {
    id: 'njengoko-ndinjalo',
    title: 'Njengoko Ndinjalo',
    album: 'Hymns & Melodies Vol. 2',
    duration: '8:42',
    audioUrl: '/audio/hymns-melodies-vol2/njengoko-ndinjalo.mp3',
    coverImage: '/images/h&m-v2-replacement.jpeg',
    releaseDate: '2024-05-22',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
      { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
    ],
  },
  {
    id: 'ubuhle',
    title: 'Ubuhle',
    album: 'Hymns & Melodies Vol. 2',
    duration: '5:45',
    audioUrl: '/audio/hymns-melodies-vol2/ubuhle.mp3',
    coverImage: '/images/h&m-v2-replacement.jpeg',
    releaseDate: '2024-05-22',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
      { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
    ],
  },
  {
    id: 'just-a-little-longer',
    title: 'Just a Little Longer',
    album: 'Hymns & Melodies Vol. 2',
    duration: '4:42',
    audioUrl: '/audio/hymns-melodies-vol2/just-a-little-longer.mp3',
    coverImage: '/images/h&m-v2-replacement.jpeg',
    releaseDate: '2024-05-22',
    platforms: [
      { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
      { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
    ],
  },
];

export const albums: Album[] = [
  {
    id: 'hymns-melodies-vol-1',
    title: 'Hymns & Melodies Vol. 1',
    artist: 'Pastor V Mboniswa',
    coverImage: '/images/h&m-replacement.jpeg',
    releaseDate: '2022-04-15',
    description: 'A powerful live worship album featuring 10 anointed hymns and melodies, recorded live to capture the spirit of worship and praise.',
    tracks: [
      {
        id: 'yamkel-indumiso',
        title: 'Yamkel\'indumiso (Live)',
        album: 'Hymns & Melodies Vol. 1',
        duration: '6:50',
        audioUrl: '/audio/hymns-melodies-vol1/yamkel-indumiso.mp3',
        coverImage: '/images/h&m-replacement.jpeg',
        releaseDate: '2024-04-15',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
          { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
        ],
      },
      {
        id: 'lalelani-izinceku',
        title: 'Lalelani Izinceku (Live)',
        album: 'Hymns & Melodies Vol. 1',
        duration: '6:10',
        audioUrl: '/audio/hymns-melodies-vol1/lalelani-izinceku.mp3',
        coverImage: '/images/h&m-replacement.jpeg',
        releaseDate: '2024-04-15',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
          { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
        ],
      },
      {
        id: 'akumnyama-xha-ukhona',
        title: 'Akumnyama Xha Ukhona (Live)',
        album: 'Hymns & Melodies Vol. 1',
        duration: '5:40',
        audioUrl: '/audio/hymns-melodies-vol1/akumnyama-xha-ukhona.mp3',
        coverImage: '/images/h&m-replacement.jpeg',
        releaseDate: '2024-04-15',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
          { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
        ],
      },
      {
        id: 'hymn-medley',
        title: 'Hymn Medley (Live)',
        album: 'Hymns & Melodies Vol. 1',
        duration: '8:36',
        audioUrl: '/audio/hymns-melodies-vol1/hymn-medley.mp3',
        coverImage: '/images/h&m-replacement.jpeg',
        releaseDate: '2024-04-15',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
          { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
        ],
      },
      {
        id: 'aneliswe',
        title: 'Aneliswe (Live)',
        album: 'Hymns & Melodies Vol. 1',
        duration: '5:56',
        audioUrl: '/audio/hymns-melodies-vol1/aneliswe.mp3',
        coverImage: '/images/h&m-replacement.jpeg',
        releaseDate: '2024-04-15',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
          { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
        ],
      },
      {
        id: 'nxa-ebizwa-ama-gama',
        title: 'Nxa Ebizwa Ama Gama (Live)',
        album: 'Hymns & Melodies Vol. 1',
        duration: '6:00',
        audioUrl: '/audio/hymns-melodies-vol1/nxa-ebizwa-ama-gama.mp3',
        coverImage: '/images/h&m-replacement.jpeg',
        releaseDate: '2024-04-15',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
          { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
        ],
      },
      {
        id: 'thixo-ova-izikhungo',
        title: 'Thixo Ova Izikhungo (Live)',
        album: 'Hymns & Melodies Vol. 1',
        duration: '5:26',
        audioUrl: '/audio/hymns-melodies-vol1/thixo-ova-izikhungo.mp3',
        coverImage: '/images/h&m-replacement.jpeg',
        releaseDate: '2024-04-15',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
          { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
        ],
      },
      {
        id: 'oko-kwanga-kulumkile',
        title: 'Oko Kwanga Kulumkile (Live)',
        album: 'Hymns & Melodies Vol. 1',
        duration: '6:38',
        audioUrl: '/audio/hymns-melodies-vol1/oko-kwanga-kulumkile.mp3',
        coverImage: '/images/h&m-replacement.jpeg',
        releaseDate: '2024-04-15',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
          { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
        ],
      },
      {
        id: 'iba-nodumo',
        title: 'Iba Nodumo (Live)',
        album: 'Hymns & Melodies Vol. 1',
        duration: '3:56',
        audioUrl: '/audio/hymns-melodies-vol1/iba-nodumo.mp3',
        coverImage: '/images/h&m-replacement.jpeg',
        releaseDate: '2024-04-15',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
          { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
        ],
      },
      {
        id: 'bulelani',
        title: 'Bulelani (Live)',
        album: 'Hymns & Melodies Vol. 1',
        duration: '6:28',
        audioUrl: '/audio/hymns-melodies-vol1/bulelani.mp3',
        coverImage: '/images/h&m-replacement.jpeg',
        releaseDate: '2024-04-15',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/in/album/hymns-melodies-vol-1/1755980904' },
          { name: 'Amazon Music', url: 'https://music.amazon.com/tracks/B0D1GBMTCL' },
        ],
      },
    ],
  },
  {
    id: 'hymns-melodies-vol-2',
    title: 'Hymns & Melodies Vol. 2',
    artist: 'Pastor V Mboniswa',
    coverImage: '/images/h&m-v2-replacement.jpeg',
    releaseDate: '2024-05-22',
    description: 'The second volume of anointed hymns and melodies, continuing the powerful worship journey with 10 inspiring tracks.',
    tracks: [
      {
        id: 'ungukumkani',
        title: 'Ungukumkani',
        album: 'Hymns & Melodies Vol. 2',
        duration: '5:34',
        audioUrl: '/audio/hymns-melodies-vol2/ungukumkani.mp3',
        coverImage: '/images/h&m-v2-replacement.jpeg',
        releaseDate: '2024-05-22',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
          { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
        ],
      },
      {
        id: 'uthweswe',
        title: 'Uthweswe',
        album: 'Hymns & Melodies Vol. 2',
        duration: '5:40',
        audioUrl: '/audio/hymns-melodies-vol2/uthweswe.mp3',
        coverImage: '/images/h&m-v2-replacement.jpeg',
        releaseDate: '2024-05-22',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
          { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
        ],
      },
      {
        id: 'thixo-ulilanga',
        title: 'Thixo Ulilanga',
        album: 'Hymns & Melodies Vol. 2',
        duration: '6:01',
        audioUrl: '/audio/hymns-melodies-vol2/thixo-ulilanga.mp3',
        coverImage: '/images/h&m-v2-replacement.jpeg',
        releaseDate: '2024-05-22',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
          { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
        ],
      },
      {
        id: 'ndingu-mfokazi',
        title: 'Ndingu Mfokazi',
        album: 'Hymns & Melodies Vol. 2',
        duration: '4:48',
        audioUrl: '/audio/hymns-melodies-vol2/ndingu-mfokazi.mp3',
        coverImage: '/images/h&m-v2-replacement.jpeg',
        releaseDate: '2024-05-22',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
          { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
        ],
      },
      {
        id: 'mnqamlezo',
        title: 'Mnqamlezo',
        album: 'Hymns & Melodies Vol. 2',
        duration: '8:15',
        audioUrl: '/audio/hymns-melodies-vol2/mnqamlezo.mp3',
        coverImage: '/images/h&m-v2-replacement.jpeg',
        releaseDate: '2024-05-22',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
          { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
        ],
      },
      {
        id: 'makabongwe',
        title: 'Makabongwe',
        album: 'Hymns & Melodies Vol. 2',
        duration: '9:39',
        audioUrl: '/audio/hymns-melodies-vol2/makabongwe.mp3',
        coverImage: '/images/h&m-v2-replacement.jpeg',
        releaseDate: '2024-05-22',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
          { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
        ],
      },
      {
        id: 'jabulani',
        title: 'Jabulani',
        album: 'Hymns & Melodies Vol. 2',
        duration: '5:05',
        audioUrl: '/audio/hymns-melodies-vol2/jabulani.mp3',
        coverImage: '/images/h&m-v2-replacement.jpeg',
        releaseDate: '2024-05-22',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
          { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
        ],
      },
      {
        id: 'njengoko-ndinjalo',
        title: 'Njengoko Ndinjalo',
        album: 'Hymns & Melodies Vol. 2',
        duration: '8:42',
        audioUrl: '/audio/hymns-melodies-vol2/njengoko-ndinjalo.mp3',
        coverImage: '/images/h&m-v2-replacement.jpeg',
        releaseDate: '2024-05-22',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
          { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
        ],
      },
      {
        id: 'ubuhle',
        title: 'Ubuhle',
        album: 'Hymns & Melodies Vol. 2',
        duration: '5:45',
        audioUrl: '/audio/hymns-melodies-vol2/ubuhle.mp3',
        coverImage: '/images/h&m-v2-replacement.jpeg',
        releaseDate: '2024-05-22',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
          { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
        ],
      },
      {
        id: 'just-a-little-longer',
        title: 'Just a Little Longer',
        album: 'Hymns & Melodies Vol. 2',
        duration: '4:42',
        audioUrl: '/audio/hymns-melodies-vol2/just-a-little-longer.mp3',
        coverImage: '/images/h&m-v2-replacement.jpeg',
        releaseDate: '2024-05-22',
        platforms: [
          { name: 'Apple Music', url: 'https://music.apple.com/cd/album/hymns-melodies-vol-2/1747267989' },
          { name: 'Amazon Music', url: 'https://music.amazon.ca/tracks/B0D4M61MM6' },
        ],
      },
    ],
  },
  {
    id: 'hymns-melodies-vol-3',
    title: 'Hymns & Melodies Vol. 3',
    artist: 'Pastor V Mboniswa',
    coverImage: '/images/h&m3-coming-soon.jpeg',
    releaseDate: '2026-07-04',
    description: 'The third volume of anointed hymns and melodies. Currently available exclusively on USB. Online release coming soon!',
    comingSoon: true,
    usbOnly: true,
    tracks: [], // Tracks will be added when album is released online
  },
];

export const sermons: Sermon[] = [];

export const events: Event[] = [
  {
    id: '4',
    title: 'Men\'s conference',
    date: '2026-04-27',
    time: '6:00 PM',
    location: 'Youth Hall',
    venue: 'Grace Community Church',
    description: 'Empowering the next generation through worship and the Word.',
    type: 'ministry',
    image: '/images/h&m-replacement.jpeg',
  },
  {
    id: '5',
    title: 'Hymns and Melodies Volume 3 Launch',
    date: '2026-07-04',
    time: '6:00 PM',
    location: 'Khayelitsha',
    venue: 'Khayelitsha',
    description: 'Empowering the next generation through worship and the Word.',
    type: 'concert',
    image: '/images/h&m3-coming-soon.jpeg',
    ticketUrl: 'https://www.webtickets.co.za/v2/event.aspx?itemid=1586190384',
  },  
  {
    id: '6',
    title: 'Night of Glory',
    date: '2026-02-15',
    time: '6:00 PM',
    location: 'Youth Hall',
    venue: 'Grace Community Church',
    description: 'Empowering the next generation through worship and the Word.',
    type: 'ministry',
    image: '/images/nog.jpg',
  },
];

export const galleryItems: GalleryItem[] = [];

export const scriptures: Scripture[] = [
  {
    verse: 'For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.',
    reference: 'Jeremiah 29:11',
  },
  {
    verse: 'I can do all things through Christ who strengthens me.',
    reference: 'Philippians 4:13',
  },
  {
    verse: 'Trust in the Lord with all your heart and lean not on your own understanding.',
    reference: 'Proverbs 3:5',
  },
];

export const socialLinks: SocialLink[] = [
  { platform: 'Facebook', url: 'https://www.facebook.com/vincentvuyile.mboniswa', icon: 'facebook' },
  { platform: 'Instagram', url: 'https://www.instagram.com/vincentm2591/', icon: 'instagram' },
  { platform: 'YouTube', url: 'https://www.youtube.com/channel/UCFJkyuDyyPcZ6n42B5Segjg', icon: 'youtube' },
  { platform: 'TikTok', url: 'https://www.tiktok.com/@pastorvmboniswa', icon: 'tiktok' },
];

export const sermonTopics = ['All', 'Faith', 'Prayer', 'Purpose', 'Encouragement', 'Worship'];
